sqlite3 reuters.db < assignment2_a.sql > part_a.txt
sqlite3 reuters.db < assignment2_b.sql > part_b.txt
sqlite3 reuters.db < assignment2_c.sql > part_c.txt
sqlite3 reuters.db < assignment2_d.sql > part_d.txt
sqlite3 reuters.db < assignment2_e.sql > part_e.txt
sqlite3 reuters.db < assignment2_f.sql > part_f.txt
sqlite3 matrix.db  < assignment2_g.sql > part_g.txt
sqlite3 reuters.db < assignment2_h.sql > part_h.txt
sqlite3 reuters.db < assignment2_i.sql > part_i.txt
